### ISSUE TITLE
Kernel panic when using net-echo with Serval

### ISSUE THREAD

**Issue by cjdoucette** [AltraMayor/XIA-for-Linux#3] opened 2014-02-28 04:02 UTC
**Description**:

kernel When trying to use the net-echo application with Serval (streaming echo using XIP), the XIA kernel panics.

**How to reproduce**:

Setup two XIA-enabled (3.11.0rc7 kernel) hosts connected via Ethernet. Insert the HID and Serval principals into each kernel. Follow the below instructions to setup the net-echo application.

Server side:
- Server HID (example): `hid-f4876ba0094167017e175f94392cf5e874caba1f`
- net-echo server instance: `serval-007f4e38904e83634acc7e1340ef7665e3f1f57a-0`

`$ ./eserv stream xip server`

On client side:
- Client HID (example): `hid-21f7cedae9821d0b45d2ce304e48f32fff47d865`
- net-echo client instance: `serval-007f4e38904e83634acc7e1340ef7665e3f1f57b-0`

```
$ sudo xip serval addroute service  007f4e38904e83634acc7e1340ef7665e3f1f57a \
gw hid-f4876ba0094167017e175f94392cf5e874caba1f
$ ./ecli stream xip client server   # kernel panic in HID module
```

**Additional Information**:
- Something bad is happening in the HID module, especially around `main_input_output`. The bug happens before trying to transmit any data (the panic occurs when the `ecli` application is started).

**Screenshot**:

![img_20140227_114855_507](https://f.cloud.github.com/assets/1501593/2290852/408ab7f8-a02c-11e3-99a3-74c9cd81ad8e.jpg)

**Comment by AltraMayor** [comment] 2014-06-27 18:33
Hi Cody,

I've tried to reproduce the kernel panic using Linux containers, but I could not. Nevertheless, I found a couple of problems with the setup:
1. While there is a routing redirect to the serer's ServalID on the client side, there's no equivalent redirect on the server side, so the echo/reply packet won't reach the client since client and server are not on the same host.
2. Even if the redirect mentioned in the previous item is inserted on the server side, Serval won't be able to establish a connection because the connection handshake is not aware of those routing redirects when it does the transition from ServalID to FlowID.

When I added the respective HIDs to the addresses of the client and the server the echo server worked as expected. In your example the client's address would be as follows:

hid-21f7cedae9821d0b45d2ce304e48f32fff47d865-1:
serval-007f4e38904e83634acc7e1340ef7665e3f1f57b-0

If you can consistently reproduce the kernel panic, could you lend me the machines?

This case is interesting because it highlights a side effect of having two XID types in Serval. I don't know if it's good or bad at this point, but it's interesting.

**Comment by cjdoucette** [comment] 2014-07-01 15:19
Hi Michel,

I am going to take another look at this, and see if I can get the error to
occur using containers after I make the changes to XLXC you suggested in
the other email. If I can't get the error reproduced there, I can give you
two of the machines to reproduce the error, as that is where the error
originally occurred for me.

As for the setup, I did not intend for the error report to contain a valid
setup. I tried to reduce the steps to only those necessary to reproduce the
panic.

Either way, I'll let you know what I find!

Best,
Cody

**Comment by AltraMayor** [comment] 2014-07-01 22:54
Hi Cody,

I've managed to reproduce the bug using two VMs. One can't trigger this bug using LXC since it requires a network card that supports offloading the calculation of the checksum field of TCP header.

Your screenshot of the kernel dump was quite useful to nail this bug.

The fix is already on the GitHub repository. If your tests confirm that the bug was fixed, please close this issue.

**Closed as completed** 2014-07-04 21:49 UTC
